### ISSUE TITLE
control width 100%

### ISSUE THREAD

**Issue by riwos** [mandhu/ngx-number-spin#2]
Hi,

I think it would be nice to have possibility to control width.. In my case I would like have 100% width..

Expected result:
<img width="414" alt="1" src="https://user-images.githubusercontent.com/684729/85874028-e8302400-b7c9-11ea-8d7c-278f38c047b2.png">

I had to remove highlighted style to achieve it:
<img width="327" alt="Screenshot 2020-06-26 at 16 25 25" src="https://user-images.githubusercontent.com/684729/85874245-3d6c3580-b7ca-11ea-9327-7b31c733110a.png">

You could add possibility to override styles or something similar to control styles..

Give me a shout what do you think about it ;)

**Comment by jrquick17** [comment]
Feel free to submit a PR otherwise I will add this feature when I have more time. Thanks!

**Comment by mandhu** [comment]
That would be nice

**Comment by jrquick17** [comment]
This has been changed and will be released in v2.2.0, allowing custom widths.

**Comment by riwos** [comment]
@jrquick17 Thanks mate for your effor ! ;)
